### PR TITLE
Fix issues pointer by github users

### LINKED ISSUE #2: Documentation on requirements
It would be nice if the readme included a couple of lines on requirements, specially the tensorflow version that this code was ran with (I'm getting an error which I'm guessing it's due to API TF breakage).

### LINKED ISSUE #18: Issue with empty sequence
I'm running several tuning jobs and some of them die with the following error (see below). It almost looks like a sentence/sequence that is generated is empty and that makes the rouge scorer to complain. Have you encounter this problem? Any experience on how to address it? It's usually deep in the training (10K+ steps). 

```
Traceback (most recent call last):
  File "train_and_eval.py", line 590, in <module>
    main()
  File "train_and_eval.py", line 173, in main
    train_and_eval(model, args)
  File "train_and_eval.py", line 282, in train_and_eval
    valid_targets)
  File "train_and_eval.py", line 333, in evaluate
    rouge = compute_rouge(valid_predictions, targets)
  File "train_and_eval.py", line 560, in compute_rouge
    scores = rouge.get_scores(hyps=predictions, refs=targets, avg=True)
  File "/opt/conda/lib/python3.6/site-packages/rouge/rouge.py", line 86, in get_scores
    return self._get_avg_scores(hyps, refs)
  File "/opt/conda/lib/python3.6/site-packages/rouge/rouge.py", line 112, in _get_avg_scores
    sc = fn(hyp, ref)
  File "/opt/conda/lib/python3.6/site-packages/rouge/rouge.py", line 55, in <lambda>
    "rouge-1": lambda hyp, ref: rouge_score.rouge_n(hyp, ref, 1),
  File "/opt/conda/lib/python3.6/site-packages/rouge/rouge_score.py", line 159, in rouge_n
    raise ValueError("Collections must contain at least 1 sentence.")
ValueError: Collections must contain at least 1 sentence.
Training exited with error code 1
```

### PR DESCRIPTION
**Pull request by CoderPat**
Fixes #2, #18, #16, #19 , #2

### CODE REVIEW

**Comment by CoderPat** [comment]
Will leave this open until I have time to test this or some other user confirms this solves the issues

**Comment by ioana-blue** [comment]
My tensorflow version complained when I used None down the line. I had to use an empty dictionary.

**Comment by CoderPat** [comment]
You mind providing the error message? It shouldn't happen...

**Comment by CoderPat** [comment]
And thank you for all the feedback provided while using the code

**Comment by CoderPat** [comment]
@ioana-blue good news, found the issue that was making your inference disaligned, should be fixed now

**Comment by ioana-blue** [comment]
@CoderPat excellent news! I'm going to try to get to this code this week. 

Can you please explain a bit the fix? I saw the removal of the params in infer, but I'm not sufficiently familiar with the code to understand the implications. I'd like to understand the code a bit more. TIA!

**Comment by CoderPat** [comment]
I was setting the shuffle buffer, which was causing the input tot be shuffled (this is used for training)

**Comment by ioana-blue** [comment]
oh, ok, that makes sense. are you ICLR results affected by this? I was using them as guidelines on where the performance I get should be.

**Comment by CoderPat** [comment]
No. The ICLR results were done mostly with OpenGNN alone. However while running the experiments, I found that the interface was a bit cumbersome for experimentation and so this repo was introduced to make life easier for people trying to replicate the paper (hence all this uncatched bugs)

**Comment by CoderPat** [comment]
If u don't mind I'll close this PR, and open a new one for the checkpoint problem

**Comment by ioana-blue** [comment]
Sounds good.

**Pull request merged**
