### PR TITLE
Fix issues pointed by other users in github

### LINKED ISSUE #1: Potential typo in the instructions in the README
First, thanks for sharing the code, saved me quite a bit of sweat :)

Second, there might be a typo in the instructions to build the vocabulary files. I'm (wild)guessing that the following lines should refer to the target file (instead of inputs):

```
ognn-build-vocab --with_sequence_tokens \
                 --save_vocab /data/naturallanguage/cnn_dailymail/output.vocab \
                 /data/naturallanguage/cnn_dailymail/split/train/inputs.jsonl.gz
```

should read

```
ognn-build-vocab --with_sequence_tokens \
                 --save_vocab /data/naturallanguage/cnn_dailymail/output.vocab \
                 /data/naturallanguage/cnn_dailymail/split/train/targets.jsonl.gz 
```
if I understand correctly what this vocab file is meant for.

### LINKED ISSUE #3: Error for Momentum optimizer
I'm getting an error when I use the momentum optimizer:
`TypeError: __init__() missing 1 required positional argument: 'momentum'`

Initially I thought was some TF API breakage, but I think the culprit is in this line:
https://github.com/CoderPat/structured-neural-summarization/blob/master/train_and_eval.py#L516

`    def optimizer(lr): return optimizer_class(lr)  # **optimizer_params)`

For momentum, the constructor expects more parameters, so I'm guessing the following fixes it:
`       def optimizer(lr): return optimizer_class(lr, **kwargs)`
and the `kwargs` are picked from the above.

### PR DESCRIPTION
**Pull request by CoderPat**
Fixes #1 ,#3, #4, #5 and #7, #12.

### CODE REVIEW

**Comment by ioana-blue** [comment]
Can't comment on the script that generates the graph, the rest look good to me. Thanks for your help!

**Comment by ioana-blue** [comment]
Note problem explained here:
https://github.com/CoderPat/structured-neural-summarization/issues/4#issuecomment-482386587

**Comment by shellycsy** [comment]
> Can't comment on the script that generates the graph, the rest look good to me. Thanks for your help!

Have you finished the experiment?

**Review by ioana-blue — COMMENTED** [review]
at line 445/444, I get an error because I think the iterator now produces only features without labels as you removed the labels_file from the input function but you're still unpacking it from the iterator. Taking an educated guess, labels should disappear from line 444

And also probably remove `labels` from the call to model. I think it should work fine with `None` for labels since it's calling the model in inference mode.

**Comment by ioana-blue** [comment]
What I see is that TF is not happy with dealing with None tensors, so a workaround may be necessary to pass in None as labels. Passing an empty dictionary should work. This means changing the code in the OpenGNN to account for empty labels as opposed to None.

**Pull request merged**
